export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const POST_ROUTE = '/post/:id'
export const CHAT_ROUTE = '/chat'
